language: ruby

rvm:
  - truffleruby-head

cache:
  bundler: true
  directories:
  - $HOME/.webdrivers

addons:
  chrome: stable
  apt:
    update: true

sudo: false
dist: xenial

rvm:
  - truffleruby-head

matrix:
  fast_finish: true

bundler_args: --jobs 3 --retry 3

before_install:
  - gem update --system
  - gem install bundler

